<?php
return [
    [
        'user_id' => null,
        'title' => 'Default Apartment Title',
        'slug' => 'default-apartment-title',
        'room' => 2,
        'beds' => 1,
        'bathroom' => 1,
        'mq' => 50,
        'address' => 'Via del Corso',
        'postal_code' => '00186',
        'civic_number' => '15',
        'city' => 'Roma',
        'longitude' => 12.496366,
        'latitude' => 41.902783,
        'img' => 'default_image.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Modern Apartment in City Center',
        'slug' => 'modern-apartment-city-center',
        'room' => 3,
        'beds' => 2,
        'bathroom' => 1,
        'mq' => 85,
        'address' => 'Piazza Venezia',
        'postal_code' => '00187',
        'civic_number' => '1',
        'city' => 'Roma',
        'longitude' => 12.492231,
        'latitude' => 41.890251,
        'img' => 'modern_apartment.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Cozy Suburban House',
        'slug' => 'cozy-suburban-house',
        'room' => 5,
        'beds' => 3,
        'bathroom' => 2,
        'mq' => 120,
        'address' => 'Via Appia Nuova',
        'postal_code' => '00179',
        'civic_number' => '110',
        'city' => 'Roma',
        'longitude' => 12.496366,
        'latitude' => 41.902783,
        'img' => 'cozy_house.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Luxury Villa by the Sea',
        'slug' => 'luxury-villa-by-sea',
        'room' => 8,
        'beds' => 6,
        'bathroom' => 4,
        'mq' => 300,
        'address' => 'Lungomare di Ostia',
        'postal_code' => '00122',
        'civic_number' => '200',
        'city' => 'Roma',
        'longitude' => 12.501980,
        'latitude' => 41.897056,
        'img' => 'luxury_villa.jpg',
        'is_visible' => false,
    ],
    [
        'user_id' => null,
        'title' => 'Charming Loft Downtown',
        'slug' => 'charming-loft-downtown',
        'room' => 2,
        'beds' => 1,
        'bathroom' => 1,
        'mq' => 45,
        'address' => 'Via dei Fori Imperiali',
        'postal_code' => '00184',
        'civic_number' => '4',
        'city' => 'Roma',
        'longitude' => 12.485338,
        'latitude' => 41.892916,
        'img' => 'loft_downtown.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Spacious Family Home',
        'slug' => 'spacious-family-home',
        'room' => 6,
        'beds' => 4,
        'bathroom' => 3,
        'mq' => 150,
        'address' => 'Via di Trastevere',
        'postal_code' => '00153',
        'civic_number' => '78',
        'city' => 'Roma',
        'longitude' => 12.471733,
        'latitude' => 41.888638,
        'img' => 'family_home.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Stylish Studio in Trendy Area',
        'slug' => 'stylish-studio-trendy-area',
        'room' => 1,
        'beds' => 1,
        'bathroom' => 1,
        'mq' => 35,
        'address' => 'Via del Pigneto',
        'postal_code' => '00176',
        'civic_number' => '45',
        'city' => 'Roma',
        'longitude' => 12.460850,
        'latitude' => 41.897738,
        'img' => 'stylish_studio.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Penthouse with Panoramic Views',
        'slug' => 'penthouse-panoramic-views',
        'room' => 4,
        'beds' => 3,
        'bathroom' => 2,
        'mq' => 110,
        'address' => 'Via Flaminia',
        'postal_code' => '00196',
        'civic_number' => '256',
        'city' => 'Roma',
        'longitude' => 12.511330,
        'latitude' => 41.902907,
        'img' => 'penthouse_views.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Quiet Countryside Cottage',
        'slug' => 'quiet-countryside-cottage',
        'room' => 4,
        'beds' => 2,
        'bathroom' => 2,
        'mq' => 95,
        'address' => 'Via della Campagna',
        'postal_code' => '00189',
        'civic_number' => '12',
        'city' => 'Roma',
        'longitude' => 12.554220,
        'latitude' => 41.901427,
        'img' => 'countryside_cottage.jpg',
        'is_visible' => false,
    ],
    [
        'user_id' => null,
        'title' => 'Historic Villa with Garden',
        'slug' => 'historic-villa-garden',
        'room' => 10,
        'beds' => 5,
        'bathroom' => 5,
        'mq' => 450,
        'address' => 'Via del Gianicolo',
        'postal_code' => '00165',
        'civic_number' => '7',
        'city' => 'Roma',
        'longitude' => 12.483970,
        'latitude' => 41.900432,
        'img' => 'historic_villa.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Minimalist Apartment with Balcony',
        'slug' => 'minimalist-apartment-balcony',
        'room' => 3,
        'beds' => 2,
        'bathroom' => 1,
        'mq' => 70,
        'address' => 'Viale delle Milizie',
        'postal_code' => '00192',
        'civic_number' => '55',
        'city' => 'Roma',
        'longitude' => 12.468332,
        'latitude' => 41.890784,
        'img' => 'minimalist_apartment.jpg',
        'is_visible' => true,
    ],
];
