<?php
return [
    [
        'user_id' => null,
        'title' => 'Default Apartment Title',
        'slug' => 'default-apartment-title',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'mq' => 50,
        'address' => 'Via del Corso 15, 00186 Roma',
        'longitude' => 12.477213,
        'latitude' => 41.909258,
        'img' => 'default_image.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Modern Apartment in City Center',
        'slug' => 'modern-apartment-city-center',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'mq' => 85,
        'address' => 'Piazza Venezia 1, 00187 Roma',
        'longitude' => 12.482035,
        'latitude' => 41.896521,
        'img' => 'modern_apartment.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Cozy Suburban House',
        'slug' => 'cozy-suburban-house',
        'rooms' => 5,
        'beds' => 3,
        'bathrooms' => 2,
        'mq' => 120,
        'address' => 'Via Appia Nuova 110, 00179 Roma',
        'longitude' => 12.511962,
        'latitude' => 41.883438,
        'img' => 'cozy_house.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Luxury Villa by the Sea',
        'slug' => 'luxury-villa-by-sea',
        'rooms' => 8,
        'beds' => 6,
        'bathrooms' => 4,
        'mq' => 300,
        'address' => 'Lungomare di Ostia 200, 00121 Roma',
        'longitude' => 12.296818,
        'latitude' => 41.721680,
        'img' => 'luxury_villa.jpg',
        'is_visible' => false,
    ],
    [
        'user_id' => null,
        'title' => 'Charming Loft Downtown',
        'slug' => 'charming-loft-downtown',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'mq' => 45,
        'address' => 'Via dei Fori Imperiali 4, 00186 Roma',
        'longitude' => 12.488386,
        'latitude' => 41.892748,
        'img' => 'loft_downtown.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Spacious Family Home',
        'slug' => 'spacious-family-home',
        'rooms' => 6,
        'beds' => 4,
        'bathrooms' => 3,
        'mq' => 150,
        'address' => 'Via di Trastevere 78, 00153 Roma',
        'longitude' => 12.469437,
        'latitude' => 41.884249,
        'img' => 'family_home.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Stylish Studio in Trendy Area',
        'slug' => 'stylish-studio-trendy-area',
        'rooms' => 1,
        'beds' => 1,
        'bathrooms' => 1,
        'mq' => 35,
        'address' => 'Via del Pigneto 45, 00176 Roma',
        'longitude' => 12.524983,
        'latitude' => 41.889372,
        'img' => 'stylish_studio.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Penthouse with Panoramic Views',
        'slug' => 'penthouse-panoramic-views',
        'rooms' => 4,
        'beds' => 3,
        'bathrooms' => 2,
        'mq' => 110,
        'address' => 'Via Flaminia 256, 00196 Roma',
        'longitude' => 12.485046,
        'latitude' => 41.951752,
        'img' => 'penthouse_views.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Quiet Countryside Cottage',
        'slug' => 'quiet-countryside-cottage',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 2,
        'mq' => 95,
        'address' => 'Via della Campagna 12, 00100 Roma',
        'longitude' => 12.610491,
        'latitude' => 41.682331,
        'img' => 'countryside_cottage.jpg',
        'is_visible' => false,
    ],
    [
        'user_id' => null,
        'title' => 'Historic Villa with Garden',
        'slug' => 'historic-villa-garden',
        'rooms' => 10,
        'beds' => 5,
        'bathrooms' => 5,
        'mq' => 450,
        'address' => 'Via del Gianicolo 7, 00165 Roma',
        'longitude' => 12.460828,
        'latitude' => 41.897764,
        'img' => 'historic_villa.jpg',
        'is_visible' => true,
    ],
    [
        'user_id' => null,
        'title' => 'Minimalist Apartment with Balcony',
        'slug' => 'minimalist-apartment-balcony',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'mq' => 70,
        'address' => 'Viale delle Milizie 55, 00192 Roma',
        'longitude' => 12.455188,
        'latitude' => 41.910359,
        'img' => 'minimalist_apartment.jpg',
        'is_visible' => true,
    ],
];
